### PR TITLE
Maintain previous scroll position

### PR DESCRIPTION
**Pull request by darangi**
### Description of the Change

Maintains scroll position after opening a file from the results page.

### Benefits

Always keep your last selected search result in focus whenever you return to the results page.

### Possible Drawbacks

None

### Applicable Issues

Fixes https://github.com/atom/find-and-replace/issues/1097

### CODE REVIEW

**Comment by darangi** [comment]
> @darangi all looking good, just make sure the test fails without your fix and you are good to go on merging this PR. Good job 🤩
Thanks! The test fails without the fix 😃

**Comment by darangi** [comment]
@lkashef  Thanks! The test fails without the fix 😃

**Comment by MadLittleMods** [comment]
Can this be pushed into a new release? ✌😇 I'm stuck scrolling over and over

**Comment by Aerijo** [comment]
@MadLittleMods I don't know where this particular PR is, but try out the beta or nightly channels if you want to use features sooner.

**Comment by MadLittleMods** [comment]
@Aerijo The last release `v0.219.1` is from 2019-11-1. How do I switch to the beta/nightly of the `find-and-replace` package? I don't see any beta tags there. I'm just assuming the `find-and-replace` package is updated independent of Atom releases?

Or are you referring to the Atom as a whole nightlies? https://blog.atom.io/2019/06/21/introducing-atom-nightly-releases.html

**Comment by Aerijo** [comment]
Ah, in that case it hasn't even come to nightly yet (Atom as a whole). What you can do now is clone the repo, run `apm install` and then `apm link` at it's root directory to use the repo in it's current state. I believe the install step will require build tools installed on your computer, for any native modules. The linked package will take priority over the builtin version (after a reload), and running `apm unlink find-and-replace` will remove this linked version and the builtin will be used again.

**Comment by danialmuqris98** [comment]
Tq

**Comment by mikkovedru** [comment]
Doesn't this commit also fixes https://github.com/atom/atom/issues/20259 ?

**Comment by nobodo** [comment]
Not sure if related to this change, but a new quirk has appeared. When there are plenty of search results, collapse all, scroll down beyond the visible ones, then expand one and follow it, return back to search tab and then collapse that item -> position jumps. After this happens, any expand/collapse event jumps the position. The only cure is to close the search tab and do the search again (unfortunately the same thing happens again, but on the positive side this should be quite easy to reproduce)

Might not happen at the very first iteration, but I can reproduce this after few expand & follow & return. Happens also with nightly build (1.48.0-nightly2). Platform is macOS.

**Comment by stwr667** [comment]
I get this too @nobodo. Really annoying when you're working through a big search list.

**Pull request merged**
