### PR TITLE
Add incremental forward and reverse search

### PR DESCRIPTION
**Pull request by mkleehammer**
This adds incremental forward (cmd-i) and reverse (cmd-shift-i) searches.

### CODE REVIEW

**Comment by benogle** [comment]
So there is now a setting to select the first match:

screen shot 2015-08-11 at 4 48 00 pm

How about making `cmd-i` and `cmd-shift-i` basically do the same thing as `cmd-g` but keep focus on the 
find and replace pattern. Would that solve your issue?

**Comment by MartinMuzatko** [comment]
isn't cmd-shift-i opening the dev tools?

**Comment by maxbrunsfeld** [comment]
@mkleehammer Thanks for your work on this; I'm going to close this one out until you get a chance to come back to it. FYI, we're planning on making big changes to this package soon to remove jQuery, so further conflicts will be created.

**Comment by mkleehammer** [comment]
Sorry, I must have missed responding.  I'm afraid I'm using Spacemacs lately so my opinion shouldn't really count anymore.  Good luck!

**Pull request closed without merging**
