### PR TITLE
add close button

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Add a close button to the Find in Current Buffer panel and the Find in Project panel

image

### Alternate Designs

Could be on the left

### Benefits

People with a 2016 Macbook pro can finally close the find-and-replace panel

### Possible Drawbacks

Takes up screen real estate. Might need to consider a setting to enable/disable it.

### Applicable Issues

#164
#204
#219
#347
#683

### CODE REVIEW

**Comment by reggieb** [comment]
+1 to this PR

**Comment by thomasjo** [comment]
> People with a 2016 Macbook pro can finally close the find-and-replace panel

This is still possible, although does require an extra keypress to reveal the function keys.

> Takes up screen real estate. Might need to consider a setting to enable/disable it.

**No**. We are not adding a setting to enable/disable a UI element.

While I'm not opposed to the notion of having a close button for the find and replace panel, from the screenshot it is obvious that the current implementation/style breaks the visual design of the panel. The current implementation therefore needs to be reworked. Additionally, this likely needs to be implemented at the core UI level. In other words, support for panel close buttons should perhaps be implemented in [atom/atom-ui](https://github.com/atom/atom-ui) first, then this PR should merely leverage the core UI functionality.

/cc @simurai @atom/feedback

**Comment by simurai** [comment]
Now that there are docks https://github.com/atom/atom/pull/13977, my ✋  vote would go towards moving find-and-replace into the bottom dock. Here a quick prototype:

find

Then the space gets shared with other bottom panels, in the above example it's Linter. You can still keep using the keyboard like you're used to, but when hovering the tab, there will be a close button. Some themes show it all the time. For people that are REALLY concerned about the extra space for the tabs could still hide them in their `styles.less` file.

Another bonus: You then even could move find-and-replace to the left or right dock. Maybe above the search results? Although that might need some style tweaks to make it look good.

**Comment by ScreamingHawk** [comment]
Just started using atom and this was the first problem I ran into. Having to look up bug report to find a hidden keyboard shortcut to do something this trivial, leaves a bad taste. Noticed people have had problems finding this since 2014 and it hasn't been addressed. 

Coming from Notepad++, IntelliJ (and derivatives)

**Comment by UziTech** [comment]
@ScreamingHawk Welcome to Atom. In the mean time you can install my package [find-and-replace-close-button](https://atom.io/packages/find-and-replace-close-button) until they have this worked out.

**Comment by jeffmcneill** [comment]
According to the above, the pr is working in the stable version, but broken in the beta version. Does that mean beta is broken or the pr code?

**Comment by 50Wliu** [comment]
Beta was broken when this PR was created (it looked in the wrong place for bundled packages).  Going to restart the build so that it uses the latest Beta version, which should fix it.

**Comment by simurai** [comment]
> my ✋  vote would go towards moving find-and-replace into the bottom dock.

It looks like find-and-replace will **not** move to the bottom dock and stay its own panel.

So here two tweaks: https://github.com/UziTech/find-and-replace/pull/1

Otherwise I'm 👍  on merging.

> @thomasjo No. We are not adding a setting to enable/disable a UI element.

Also, ok with that, since hiding the close button could also be a done with `.find-and-replace .close-button { display: none; }` in your `styles.less`. For those that _really_ don't like it.

**Comment by UziTech** [comment]
I removed the commit for the enable/disable setting and added the changes in https://github.com/UziTech/find-and-replace/pull/1

**Comment by maxbrunsfeld** [comment]
Thanks @UziTech! Nice work.

**Comment by simurai** [comment]
Ok, so for people that really ~hate~ dislike the close button, you can add this line to your `styles.less` and it should disappear:

```less
// hide find+replace close button
.find-and-replace .close-button { display: none; }
```

**Pull request merged**
