### PR TITLE
Prevent 'getSelectedBufferRanges' uncaught exception

### LINKED ISSUE #619: Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0
**System**: Ubuntu 14.04.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.194.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

```
At /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:788

TypeError: Cannot read property 'getSelectedBufferRanges' of null
    at FindView.module.exports.FindView.anyMarkersAreSelected (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:788:36)
    at FindView.anyMarkersAreSelected (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
    at FindView.module.exports.FindView.toggleCaseOption (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:808:17)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:45.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.3.0 find-and-replace:show (div.panels)
  2x -0:24 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:23.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.6.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -0:17.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:17.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:16.3.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 find-and-replace:focus-previous (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:11.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.8
linter, v1.11.3

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by naegi**
This PR just fixes #619

### CODE REVIEW

**Comment by lee-dohm** [comment]
Is it possible to create a spec for this?

**Comment by naegi** [comment]
#Problem
Find and replace crash when you try to toogle options such as regex in a non-text tab (i.e img,etc. Cf repro in #619)

#Correction
If the tab isn't a text tab, the editor object will be none I just had to handle it in anyMarkersAreSelected. Futhermore, there is no markers available, so, handle this in selectFirstMarker*

Sorry for my bad english

**Comment by lee-dohm** [comment]
What I meant was, can you write some automated tests to ensure that we don't accidentally break this fix in the future?

**Comment by naegi** [comment]
Done
Sorry, I had no time to write that before now.

**Comment by lee-dohm** [comment]
Thanks for contributing!

**Pull request merged**
