### PR TITLE
Add logic to consume file-icons service

### PR DESCRIPTION
**Pull request by Alhadis**
[Same affair as before](https://github.com/atom/fuzzy-finder/pull/211). Hooks the `find-and-replace` package up to the icon-service, allowing packages to customise the file-icons that're displayed in project search results.

### CODE REVIEW

**Comment by Alhadis** [comment]
@as-cii Could you give this a review too, if it's not too much trouble? 0=) Once this and atom/archive-view#37 gets merged, that'll be the entire icons API catered for.

**Comment by Alhadis** [comment]
@50Wliu Any chance of having this looked at *this year*? Serious question.

**Comment by maxbrunsfeld** [comment]
Hey, sorry for the delay @Alhadis. This looks great.

**Comment by maxbrunsfeld** [comment]
This will go out in the next beta release.

**Comment by Alhadis** [comment]
Thank you!!!

**Pull request merged**
