### PR TITLE
Serialize / remember the open panel on reload

### LINKED ISSUE #393: Bug: File/directory pattern is reseted after I reload/reopen Atom editor
When I reload or reopen Atom editor "File/directory pattern" field is always empty.
It should contain the last used pattern for easy search in the project.

It also doesn't have a history, so I can't choose previous used patterns.

### PR DESCRIPTION
**Pull request by benogle**
For forever we have not been properly serializing the find and replace panels. It wouldnt remember if you had a panel open, and it wouldnt remember the text you had in any of the boxes. This PR allows the correct panel to open up on an atom window reload / restart.

Note: 
- I removed the activation commands. `activate()` is run all the time. I've tried to keep it fast. On my machine it takes 13ms to activate.

_Here's a seizure inducing gif_
fnr-serialize

This is a WIP. I would like people to try this out if possible and see if it's helpful or annoying. cc @atom/feedback 

TODO
- [x] Make it work
- [ ] Come to consensus on whether we should or shouldnt do this
- [ ] Fix Specs, add a spec or two

Closes #393 
Closes #426

### CODE REVIEW

**Comment by benogle** [comment]
cc @atom/feedback Anyone opposed to this? Should we start with a fresh, unopened find panel on every new window?

**Comment by 50Wliu** [comment]
Can this be made an option?  I'm not 100% sure I'd like having the find box re-open after I close and restart Atom.

**Comment by benogle** [comment]
Yeah, we can make an option for a while

**Comment by maxbrunsfeld** [comment]
👋  @benogle. Gonna close this out for now. I'm trying to clear things out before we :fire: jQuery.

**Comment by benogle** [comment]
:boom:

**Pull request closed without merging**
