### PR TITLE
Ignore pane items that aren't text editors

### LINKED ISSUE #582: Uncaught TypeError: this.editor.scanInBufferRange is not a function
This happens with the https://github.com/markushedvall/plantuml-viewer package installed, after I've used find/replace once. This keeps appearing even after find/replace is closed again.

**Atom Version**: 1.1.0
**System**: FANNON-WORK
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.185.0
### Stack Trace

Uncaught TypeError: this.editor.scanInBufferRange is not a function

```
At C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:155

TypeError: this.editor.scanInBufferRange is not a function
  at BufferSearch.module.exports.BufferSearch.createMarkers (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:155:23)
  at BufferSearch.module.exports.BufferSearch.recreateMarkers (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:140:26)
  at BufferSearch.module.exports.BufferSearch.setEditor (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:63:19)
  at C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\find.js:69:36
  at Emitter.module.exports.Emitter.emit (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:333:27
  at Pane.module.exports.Pane.observeActiveItem (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:195:7)
  at C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:331:42
  at Emitter.module.exports.Emitter.emit (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:196:22)
  at Pane.module.exports.Pane.activate (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:616:15)
  at space-pen-div.<anonymous> (C:\Users\Fannon\.atom\packages\plantuml-viewer\lib\plantuml-viewer-view.js:43:48)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -1:58.9.0 core:copy (atom-text-editor.editor.is-focused)
     -1:56.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:52.7.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:50.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:45.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:44.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:37.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:35.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:35.7.0 editor:upper-case (atom-text-editor.editor)
     -1:29.6.0 core:copy (atom-text-editor.editor.is-focused)
     -1:00.6.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:56.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:51.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:33 core:copy (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.16
atom-handlebars, v1.2.0
atom-pair, v2.0.10
color-picker, v2.0.13
emmet, v2.3.13
language-mediawiki, v2.0.0
language-plantuml, v0.1.1
linter, v1.10.0
linter-js-yaml, v1.2.0
linter-markdown, v1.2.1
linter-php, v1.0.5
linter-sass-lint, v0.4.1
minimap, v4.16.0
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
nucleus-dark-ui, v0.6.6
pigments, v0.18.1
plantuml-viewer, v0.7.0

# Dev
No dev packages
```

### LINKED ISSUE #649: Error while working with PlantUML
Happens on every drag of pretty big plantuml diagram when search'n'replace is opened

**Atom Version**: 1.4.0
**System**: Ubuntu 15.10
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.194.0
### Stack Trace

Uncaught TypeError: this.editor.scanInBufferRange is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:183

TypeError: this.editor.scanInBufferRange is not a function
    at BufferSearch.module.exports.BufferSearch.createMarkers (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:183:23)
    at BufferSearch.module.exports.BufferSearch.recreateMarkers (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:168:26)
    at BufferSearch.module.exports.BufferSearch.setEditor (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:76:19)
    at /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find.js:73:36
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:196:7)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:331:42
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/usr/share/atom/resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:623:15)
    at space-pen-div.<anonymous> (/home/finkel/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
  2x -2:14.5.0 plantuml-viewer:toggle (div.plantuml-viewer.native-key-bindings)
     -0:41 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:33.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:delete (atom-text-editor.editor.is-focused)
  6x -0:31.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:30.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:24.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:24.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:24.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:21.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:21.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:21.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:08.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
angularjs-snippets, v0.10.18
data-atom, v0.18.1
emmet, v2.4.0
language-ansible, v0.1.3
language-mongodb, v0.3.1
language-plantuml, v0.2.0
linter, v1.11.3
linter-ansible-linting, v1.1.0
plantuml, v0.1.2
plantuml-viewer, v0.7.0

# Dev
No dev packages
```

### LINKED ISSUE #679: Uncaught TypeError: (intermediate value) is not a function
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.195.0
### Stack Trace

Uncaught TypeError: (intermediate value) is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:189

TypeError: (intermediate value) is not a function
    at BufferSearch.module.exports.BufferSearch.createMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:183:23)
    at BufferSearch.module.exports.BufferSearch.recreateMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:168:26)
    at BufferSearch.module.exports.BufferSearch.setEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:76:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:73:36
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:634:15)
    at space-pen-div.<anonymous> (/Users/robsnydermiletwo/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
  2x -5:07.2.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -4:56.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:23.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:49.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:51.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:50.5.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -2:40.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:30.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:22.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:06.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:01.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:44.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35.8.0 spell-check:correct-misspelling (atom-text-editor.editor.is-focused)
  2x -0:27.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.26
plantuml-viewer, v0.7.0
script, v3.5.2

# Dev
No dev packages
```

### LINKED ISSUE #815: Uncaught TypeError: this.editor.getSelectedBufferRange is not a function
### Steps to reproduce

1. Use plantuml-viewer, execute it to display the class diagram.
2. Move around in the class diagram buffer.
3. Go back to the buffer where the text is (the text from the diagram).
4. Use the search and replace function.
5. Now each time you click on the class diagram buffer you'll get the error.

It doesn't happen before using the search and replace function. But as soon
as you used it once, it will display the error each time you go back to the
class diagram buffer.

I don't know if I should report the issue here or on the plantuml-viewer's
github.

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Debian GNU/Linux
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.202.2

### Stack Trace

Uncaught TypeError: this.editor.getSelectedBufferRange is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:169

TypeError: this.editor.getSelectedBufferRange is not a function
    at BufferSearch.module.exports.BufferSearch.createMarkers (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:169:82)
    at BufferSearch.module.exports.BufferSearch.recreateMarkers (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:159:26)
    at BufferSearch.module.exports.BufferSearch.setEditor (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:71:19)
    at /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find.js:45:36
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:437:21)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)
```

### Commands

```
     -2:01.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:01.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:15.3.0 atomic-emacs:set-mark (atom-text-editor.editor.is-focused)
 13x -1:15.2.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
  2x -1:13.8.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
  3x -1:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:11.4.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:10.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:55 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.2.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -0:29.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:20.7.0 editor:newline (atom-text-editor.editor.is-focused)
 15x -0:19.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*~"
    ],
    "projectHome": "/home/edouard/Projects/",
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.9.2 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-php, v0.3.7 (active)
git-plus, v5.25.3 (active)
language-doxygen, v0.2.1 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-gcc, v0.6.15 (active)
linter-jshint, v3.0.1 (active)
linter-php, v1.3.1 (active)
livereload, v0.4.4 (active)
pigments, v0.37.0 (active)
plantuml-viewer, v0.7.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

### LINKED ISSUE #898: Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined
### Description
This error showed when I created a new [plantuml viewer](https://github.com/markushedvall/plantuml-viewer) pane and moved it. After that, when I tried with another pane to see if the problem isn't due to plantuml viewer, I kept having this error and had some panes literally destroyed (atom/atom error: destroyed pane).

I restarted my editor and everything is working fine now, can't reproduce the bug any more. Note that I upgraded to Atom 1.17.0 an hour before the bug occurred, maybe it has something to do with it.

Thank you for reading this, have a nice day.

### Steps to Reproduce
1. Create a new pane or grab an opened one
2. Move it

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.207.6

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /usr/share/atom/resources/app/node_modules/find-and-replace/lib/buffer-search.js:66

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at BufferSearch.setEditor (/usr/share/atom/resources/app/node_modules/find-and-replace/lib/buffer-search.js:66:1)
    at /usr/share/atom/resources/app/node_modules/find-and-replace/lib/find.js:61:1
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/src/workspace.js:489:1)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/share/atom/resources/app/src/workspace-center.js:16:1)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:280:1)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:318:1)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:539:1)
    at Pane.module.exports.Pane.moveItemToPane (/usr/share/atom/resources/app/src/pane.js:655:1)
    at Object.end (/usr/share/atom/resources/app/node_modules/tabs/lib/layout.js:63:1)
    at HTMLLIElement.TabView.element.ondragend (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-view.js:62:1)
```

### Commands

```
     -0:40.4.0 intentions:highlight (input.hidden-input)
     -0:40.4.0 core:copy (input.hidden-input)
     -0:39.6.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:39.1.0 intentions:highlight (input.hidden-input)
     -0:39 core:paste (input.hidden-input)
     -0:37.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:confirm (input.hidden-input)
     -0:33.6.0 intentions:highlight (input.hidden-input)
     -0:33.3.0 command-palette:toggle (input.hidden-input)
     -0:32.2.0 editor:consolidate-selections (input.hidden-input)
     -0:32.2.0 core:cancel (input.hidden-input)
     -0:31.6.0 intentions:highlight (input.hidden-input)
     -0:31.4.0 command-palette:toggle (input.hidden-input)
     -0:30.7.0 editor:consolidate-selections (input.hidden-input)
     -0:30.7.0 core:cancel (input.hidden-input)
     -0:30 plantuml-viewer:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
file-icons 2.1.6 
grammar-token-limit 0.1.1 
intentions 1.1.2 
kite 0.23.0 
language-latex 1.0.0 
language-plantuml 0.2.0 
language-restructuredtext 1.1.0 
linter 2.1.4 
linter-pylama 0.8.20 
linter-ui-default 1.5.4 
markdown-preview-enhanced 0.12.3 
markdown-table-formatter 2.9.0 
markdown-themeable-pdf 1.2.0 
minimap 4.28.2 
monokai 0.24.0 
pigments 0.39.1 
plantuml-viewer 0.7.1 
python-indent 1.0.2 
python-tools 0.6.9 
react 0.16.2 
toggle-gutter 0.3.3 
```

### PR DESCRIPTION
**Pull request by howyi**
This PR fixes #898 #815 #679 #649 #582

### Description of the Change

_Edited by @50Wliu_
BufferSearch only works on TextEditors, but we were mistakenly trying to set an editor for BufferSearch for any pane item that implemented the `getBuffer` method. We now explicitly check to make sure the new pane item is a TextEditor before setting BufferSearch's editor.

### Alternate Designs
- Add to `observeActivePaneItem` check exist `this.editor.buffer`
Because `setEditor(editor)` use this.
https://github.com/howyi/find-and-replace/blame/master/lib/buffer-search.js#L45

### Benefits
- usable PlantUML Viewer

### Possible Drawbacks
I don't see any 🐎 

### Applicable Issues
Fixes #898
Fixes #815
Fixes #679
Fixes #649
Fixes #582

### CODE REVIEW

**Comment by realthargor** [comment]
@jasonrudolph Would be awesome if this would get a review and approval. Not sure who else to ping, couldn't find anything in contribution and you seem to be active here.

**Comment by 50Wliu** [comment]
@howyi would it be more appropriate to use `this.editor.getBuffer()` in `setEditor` since that's what the conditional is checking for?

**Comment by howyi** [comment]
@50Wliu 
> use this.editor.getBuffer() in setEditor

Changed! 😃

**Comment by 50Wliu** [comment]
All right, so plantuml-viewer is creating a [`PlantumlViewerEditor`](https://github.com/markushedvall/plantuml-viewer/blob/v0.7.2/lib/plantuml-viewer-editor.js#L9) that has a `getBuffer` method, but find-and-replace is assuming that any object with `getBuffer` is a [`TextEditor`](https://atom.io/docs/api/v1.33.1/TextEditor).

I _think_ it would make sense to change the guard from `paneItem?.getBuffer?()` to `paneItem instanceof TextEditor`. Here's a diff:
```diff
diff --git a/lib/find.coffee b/lib/find.coffee
index 245a4fc..56a309e 100644
--- a/lib/find.coffee
+++ b/lib/find.coffee
@@ -1,4 +1,4 @@
-{CompositeDisposable, Disposable, TextBuffer} = require 'atom'
+{CompositeDisposable, Disposable, TextBuffer, TextEditor} = require 'atom'

 SelectNext = require './select-next'
 {History, HistoryCycler} = require './history'
@@ -30,7 +30,7 @@ module.exports =
     @resultsModel = new ResultsModel(@findOptions)

     @subscriptions.add atom.workspace.getCenter().observeActivePaneItem (paneItem) =>
-      if paneItem?.getBuffer?()
+      if paneItem instanceof TextEditor
         @findModel.setEditor(paneItem)
       else
         @findModel.setEditor(null)
```

If you agree with that, I'll start working on some updated specs for the new guard.

**Comment by howyi** [comment]
@50Wliu Thank you ! 🥇 
> If you agree with that, I'll start working on some updated specs for the new guard.

I agree, and fixed `if paneItem?.getBuffer?()` to `if paneItem instanceof TextEditor`.
Please update specs!

**Comment by 50Wliu** [comment]
Okay, I can confirm that this new fix resolves the onDidStopChanging bug, and that the spec fails when the change is reverted. @howyi does everything look good to you?

**Comment by howyi** [comment]
@50Wliu Yes! this is a good fix for me.

**Comment by 50Wliu** [comment]
Thanks! 🌟

**Comment by realthargor** [comment]
@50Wliu @howyi Thanks a lot :)

**Pull request merged**
