### PR TITLE
Reset search query when initialised

### PR DESCRIPTION
**Pull request by Alhadis**
This PR fixes a rather esoteric bug that blocks a user from rerunning the session's last buffer search.

## Steps to reproduce
1. Open a project file in Atom, and search for something that will match
2. Close project
3. Reopen project and project's file
4. Bring up the buffer search and enter the last search term verbatim. This should be done quickly, either by typing fast or pressing the <kbd>Up Arrow</kbd> key to access search history.
5. Hit <kbd>Enter</kbd>

**Expectation:** Markers should appear in the buffer
**Reality:** The program beeps at you as if the field was left blank

### CODE REVIEW

**Comment by 50Wliu** [comment]
I can confirm both that the bug exists and that this PR fixes said bug.  However, looking at replacePattern and pathsPattern, does the bug manifest there as well?

**Comment by Alhadis** [comment]
Nope. Those properties [aren't checked](https://github.com/atom/find-and-replace/blob/master/lib/buffer-search.coffee#L20-L25) in BufferSearch's `onDidChange` callback. I also tested this to see if they *did* need changing, which they didn't.

**Comment by 50Wliu** [comment]
Not familiar with this code, so please bear with me.

Then can we simply remove `changedParams.findPattern?` from that onDidChange block?  Because it looks like everything else there are actual *options*.

**Comment by Alhadis** [comment]
Hrm yeah, you're right, actually. [From a glance](https://github.com/atom/find-and-replace/commit/ef0f673dfc72715546b26c14d20a326464025a54), it would seem there was a bit of copy+paste going on, so I'd say that check can be dropped. :)

**Comment by Alhadis** [comment]
Oh! No, wait, it's needed because it represents the current state.

It should probably be called `SearchState` or something like that...

**Comment by 50Wliu** [comment]
Can you clarify on what the "state" is?

**Comment by Alhadis** [comment]
Well for lack of a better word, I mean "state" as in "the state of the user's search criteria". E.g., the find-field, replace-field, and the options affecting their usage.

**Pull request closed without merging**
