### PR TITLE
Unescape escape sequence once on replacing buffer using regex

### LINKED ISSUE #739: "\\n" in replace string generates line ending after second match
Before "Replace All":
screenshot 2016-06-08 13 16 33
After "Replace All":
screenshot 2016-06-08 13 16 43

### PR DESCRIPTION
**Pull request by norio-nomura**
Fix #739

### CODE REVIEW

**Comment by 50Wliu** [comment]
Thanks for this @norio-nomura - can you please also add some specs so that we can make sure this behavior doesn't regress?

**Comment by norio-nomura** [comment]
Added spec. 😃

**Comment by 50Wliu** [comment]
Also fixes #615.

**Comment by norio-nomura** [comment]
Thanks! :pray:

**Pull request merged**
