### PR TITLE
Watch paths to remove results on file deletion

### PR DESCRIPTION
**Pull request by acontreras89**
**WORK IN PROGRESS** 

Fixes https://github.com/atom/find-and-replace/issues/634.

Current specs are failing when adding results manually ([like here](https://github.com/atom/find-and-replace/blob/master/spec/results-view-spec.coffee#L69)), as `node-patwatcher` is unable to watch the path.
Specs for the introduced change are missing.

### CODE REVIEW

**Comment by lee-dohm** [comment]
This looks pretty good. You may want to wrap the pathwatcher stuff in `Disposables` and `CompositeDisposables`:

https://atom.io/docs/api/v1.7.1/Disposable#instance-constructor

This would make cleaning up at the end much easier.

**Comment by acontreras89** [comment]
Hey @lee-dohm, thanks for your comments.
I see how I could encapsulate each _watcher_ inside a `Disposable`. However, since I need to close them individually at some points (i.e. when a file is deleted,) I don't see how I could be using a `CompositeDisposable` to aggregate them. Can you point me in the right direction?

Oh, and I'll be updating existing specs and adding the new ones soon.

**Comment by lee-dohm** [comment]
@acontreras89 Yep, you're right :grinning:

**Comment by maxbrunsfeld** [comment]
@acontreras89 I'm going to close this one out for the time being, until you get a chance to come back to it. It's a cool idea. FYI, we're planning on making some big changes to this package soon, to remove jQuery, so further conflicts may be created.

**Comment by acontreras89** [comment]
Hello @maxbrunsfeld
I'd like to finish this, but I haven't contributed to atom in a while, so I'm feeling a bit rusty. Can you point me in the right direction to (1) find a way around current specs failing and (2) adding tests for this?

**Pull request closed without merging**
