### PR TITLE
Feature: whole word option

### PR DESCRIPTION
**Pull request by abe33**
As requested in #195

Many things are open to suggestions, like the option button label or the key bindings.
- [x] Implement the whole-word search.
- [x] Handle serialization of the whole-word option state.
- [x] Add an option button and adjust styles of the group so that it can fit in it.
- [x] Display the whole-word option state in the label.

Don't hesitate to comment if you see anything that is missing.

### CODE REVIEW

**Comment by jeffschwartz** [comment]
Don't see this find in project. Should be imo. Makes refactoring whole project easier.

**Comment by ArnaudRinquin** [comment]
Same, I don't know where to access it. Any idea?

**Comment by lee-dohm** [comment]
1. From the menu: `Find > Find in Project`
1. From the Command Palette: `Project Find: Toggle`
1. On OS X you can use the keybinding <kbd>Shift+Cmd+F</kbd> (I believe it is <kbd>Ctrl+Shift+F</kbd> on other platforms)

**Comment by jeffschwartz** [comment]
I'm sorry, perhaps I should have been more specific. I don't see the option to 'find by whole words' for project find.

**Comment by lee-dohm** [comment]
Ah ok, sorry ... my eyes must still be sleepy :grinning:

It seems this only added it for non-project find. Would you mind opening a new issue?

**Comment by jeffschwartz** [comment]
Sure, no problem.

**Pull request merged**
