### PR TITLE
Option to enable autocompletion

### PR DESCRIPTION
**Pull request by wvanlint**
Continuation of #922

### CODE REVIEW

**Comment by 50Wliu** [comment]
Here's something I noticed while this was enabled:
Searching for something that triggers autocomplete, then confirming the search without also confirming the autocomplete (e.g. by using the Find button) does not remove the autocomplete list.  That was visually jarring for me as I expected that the autocompletions would disappear after starting the search.

**Comment by nathansobo** [comment]
@50Wliu do you think it's a big enough problem that we should hold this back? I think I'm okay letting people play with it as the non-default, but I agree that it needs more work to be fully usable.

**Comment by 50Wliu** [comment]
I think that should be fixed before the option becomes on by default, but I'm fine with dealing with it while it's still experimental.

**Comment by nathansobo** [comment]
Thanks for adding the option @wvanlint. Any interest in taking on some of the usability challenges so we can enable it by default?

**Pull request merged**
